# general settings
name: RealDenoising_Restormer
model_type: ImageCleanModel
scale: 1
num_gpu: 1  # Chạy trên 1 GPU
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
    # ĐƯỜNG DẪN DỮ LIỆU (Giữ nguyên theo Kaggle của bạn)
    dataroot_gt: /kaggle/input/hybrid-squence/hybrid_sequence/train/gt
    dataroot_lq: /kaggle/input/hybrid-squence/hybrid_sequence/train/lq
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # Data Loader Settings
    use_shuffle: true
    num_worker_per_gpu: 2  # Giảm xuống 2 để tiết kiệm CPU/RAM
    batch_size_per_gpu: 2  # <--- QUAN TRỌNG: Giữ ở mức 2 để không bị OOM trên P100

    # ### ------------- TẮT Progressive training (Gây OOM) ----------------
    # mini_batch_sizes: [8,5,4,2,1,1]             
    # iters: [92000,64000,48000,36000,36000,24000]
    # gt_size: 384   
    # gt_sizes: [128,160,192,256,320,384] 
    # ### -----------------------------------------------------------------

    # ## ------- BẬT Training cố định (Fixed-patch size) ------------------
    # Cấu hình này giúp ổn định bộ nhớ. 
    # Dù ảnh gốc là 256, ta cắt 128 để train giúp tăng số lượng mẫu học (Augmentation).
    mini_batch_sizes: [2]   # Khớp với batch_size_per_gpu ở trên
    iters: [10]             # Số vòng lặp (Khớp với total_iter bên dưới)
    gt_size: 128            # Kích thước cắt: 128x128 (An toàn cho VRAM)
    gt_sizes: [128]
    # ## ------------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: /kaggle/input/hybrid-squence/hybrid_sequence/val/gt
    dataroot_lq: /kaggle/input/hybrid-squence/hybrid_sequence/val/lq
    io_backend:
      type: disk

# network structures
network_g:
  type: Restormer
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [4,6,6,8]
  num_refinement_blocks: 4
  heads: [1,2,4,8]
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: BiasFree
  dual_pixel_task: False

# path
path:
  # Đường dẫn model pre-train
  pretrain_network_g: /kaggle/working/Restormer/Denoising/pretrained_models/real_denoising.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 10          # Đang để 10 để test nhanh. Khi train thật hãy tăng lên (vd: 20000)
  warmup_iter: -1         # no warm up
  use_grad_clip: true

  # Lịch trình học (Scheduler)
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [92000, 208000]       
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]   
  
  # Data Augmentation (Trộn ảnh)
  mixing_augs:
    mixup: true
    mixup_beta: 1.2
    use_identity: true

  # Optimizer
  optim_g:
    type: AdamW
    lr: !!float 3e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  # Losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 8
  val_freq: 20           # Kiểm tra (Validate) sau mỗi 5 vòng (để test nhanh)
  save_img: true          # Lưu ảnh kết quả để xem
  rgb2bgr: true
  use_image: false
  max_minibatch: 8

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 1           # In log sau mỗi 1 vòng
  save_checkpoint_freq: 5.0 # Lưu model sau mỗi 5 vòng
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500