# general settings
name: RealDenoising_Restormer
model_type: ImageCleanModel
scale: 1
num_gpu: 1  # Chạy trên 1 GPU
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
    # ĐƯỜNG DẪN DỮ LIỆU
    dataroot_gt: /kaggle/input/hybrid-squence/hybrid_sequence/train/gt
    dataroot_lq: /kaggle/input/hybrid-squence/hybrid_sequence/train/lq
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # Data Loader Settings
    use_shuffle: true
    num_worker_per_gpu: 2  # Giữ mức 2 tiết kiệm RAM
    batch_size_per_gpu: 2  # Giữ mức 2 an toàn cho P100 (16GB)

    # ### ------------- CẤU HÌNH FIXED-PATCH SIZE ------------------
    mini_batch_sizes: [2]   # Batch size cố định
    iters: [30000]          # <--- CHỐT: 30,000 vòng lặp
    gt_size: 128            # Kích thước ảnh cắt 128x128
    gt_sizes: [128]
    # ### ----------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: /kaggle/input/hybrid-squence/hybrid_sequence/val/gt
    dataroot_lq: /kaggle/input/hybrid-squence/hybrid_sequence/val/lq
    io_backend:
      type: disk

# network structures
network_g:
  type: Restormer
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [4,6,6,8]
  num_refinement_blocks: 4
  heads: [1,2,4,8]
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: BiasFree
  dual_pixel_task: False

# path
path:
  # Đường dẫn model pre-train (nhớ kiểm tra lại đường dẫn này trên Kaggle của bạn)
  pretrain_network_g: /kaggle/working/Restormer/Denoising/pretrained_models/real_denoising.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 30000       # <--- CHỐT: Tổng cộng 30,000 vòng
  warmup_iter: -1         # no warm up
  use_grad_clip: true

  # Lịch trình học (Scheduler) - Đã chỉnh lại cho khớp với 30k
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [30000]       # Chu kỳ học là 30,000 vòng (giảm LR từ 3e-4 về 1e-6)
    restart_weights: [1]
    eta_mins: [0.000001]   
  
  # Data Augmentation
  mixing_augs:
    mixup: true
    mixup_beta: 1.2
    use_identity: true

  # Optimizer
  optim_g:
    type: AdamW
    lr: !!float 3e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  # Losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 8
  val_freq: 10000         # <--- CHỐT: Kiểm tra tại vòng 15,000 và 30,000
  save_img: true          # Lưu ảnh kết quả để ngắm nghía
  rgb2bgr: true
  use_image: false
  max_minibatch: 8

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100         # In log mỗi 100 vòng (cho đỡ rác màn hình)
  save_checkpoint_freq: 5000 # Lưu model dự phòng mỗi 5,000 vòng (để rủi ro crash thì còn có cái dùng)
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500